# Generated by Django 5.0.14 on 2026-05-10 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_instructor_userprofile_quizsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['title'], name='courses_cou_title_6e78a2_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='courses_cou_categor_fec4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level'], name='courses_cou_level_bf0a39_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published'], name='courses_cou_is_publ_4b99b9_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor'], name='courses_cou_instruc_d2e347_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_cou_slug_2e551f_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user'], name='courses_enr_user_id_6911bd_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course'], name='courses_enr_course__a70609_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['email'], name='courses_enr_email_ca1d94_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrolled_at'], name='courses_enr_enrolle_4b9ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user'], name='courses_qui_user_id_30e22b_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['course'], name='courses_qui_course__026d68_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['email'], name='courses_qui_email_8f03f3_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['submitted_at'], name='courses_qui_submitt_fef754_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['score'], name='courses_qui_score_d26269_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['user'], name='courses_qui_user_id_c84425_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['course'], name='courses_qui_course__469d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['started_at'], name='courses_qui_started_6a13ac_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['is_completed'], name='courses_qui_is_comp_e9033b_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['user', 'course'], name='courses_qui_user_id_5986fd_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='courses_use_user_id_db620e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='courses_use_role_bc9fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_verified'], name='courses_use_is_veri_aa8ecf_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['verification_status'], name='courses_use_verific_1afcb8_idx'),
        ),
    ]
