# Generated by Django 4.2.30 on 2026-05-12 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_add_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours_spent', models.FloatField(default=0)),
                ('courses_completed', models.PositiveIntegerField(default=0)),
                ('average_quiz_score', models.FloatField(default=0)),
                ('total_quiz_attempts', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Analytics',
                'verbose_name_plural': 'Student Analytics',
                'indexes': [models.Index(fields=['user'], name='courses_stu_user_id_230831_idx'), models.Index(fields=['last_activity'], name='courses_stu_last_ac_f487dd_idx'), models.Index(fields=['average_quiz_score'], name='courses_stu_average_991bc5_idx')],
            },
        ),
    ]
