# Generated by Django 5.2.14 on 2026-05-14 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_studentanalytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_lessons_count', models.PositiveIntegerField(default=0)),
                ('quizzes_passed', models.PositiveIntegerField(default=0)),
                ('total_lessons', models.PositiveIntegerField(default=0)),
                ('total_quizzes', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='zoom_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='material_file',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='material_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(help_text='URL to your GitHub repository with the final project code.')),
                ('description', models.TextField(blank=True, help_text='Brief description of your project.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to='courses.course')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Module Quiz', max_length=140)),
                ('description', models.TextField(blank=True)),
                ('pass_percentage', models.PositiveIntegerField(default=80)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course')),
            ],
            options={
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('choice_a', models.CharField(max_length=160)),
                ('choice_b', models.CharField(max_length=160)),
                ('choice_c', models.CharField(max_length=160)),
                ('choice_d', models.CharField(max_length=160)),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('order', models.PositiveIntegerField(default=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz')),
            ],
            options={
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='quizsession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='courses.quiz'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='courses.quiz'),
        ),
        migrations.AlterUniqueTogether(
            name='quizsession',
            unique_together={('user', 'course', 'quiz')},
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['passed'], name='courses_qui_passed_5e1612_idx'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.course'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='projectsubmission',
            index=models.Index(fields=['user'], name='courses_pro_user_id_1f4866_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsubmission',
            index=models.Index(fields=['course'], name='courses_pro_course__1316e4_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsubmission',
            index=models.Index(fields=['submitted_at'], name='courses_pro_submitt_684fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsubmission',
            index=models.Index(fields=['is_approved'], name='courses_pro_is_appr_27dea4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectsubmission',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['course'], name='courses_qui_course__ac0918_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_active'], name='courses_qui_is_acti_3bda0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('course', 'order')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz'], name='courses_que_quiz_id_cb00f4_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['order'], name='courses_que_order_cede08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'order')},
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user'], name='courses_use_user_id_a256e9_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['course'], name='courses_use_course__a11bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['is_completed'], name='courses_use_is_comp_dc5b4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'course')},
        ),
    ]
